CREATE TABLE person
(
    id         INTEGER NOT NULL,
    name       VARCHAR(255) NOT NULL,
    location   VARCHAR(255),
    birth_date TIMESTAMP,
    primary key (id)
);


INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE)
VALUES(10001, 'Ranga', 'Hyderabad', CURRENT_TIMESTAMP());

INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE)
VALUES(10002, 'Ahmed', 'Cairo', CURRENT_TIMESTAMP());

INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE)
VALUES(10003, 'Mohamed', 'Alexandria', CURRENT_TIMESTAMP());

INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE)
VALUES(10004, 'Ali', 'Giza', CURRENT_TIMESTAMP());

INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE)
VALUES(10005, 'Omar', 'Suez', CURRENT_TIMESTAMP());